// Package searchapi is a typed HTTP client for the hev-shop search service.
//
// The body of this package is generated by oapi-codegen v2 from the
// committed OpenAPI spec at ../../../search/openapi.json. Regenerate with:
//
//	make codegen   # or: go generate ./...
package searchapi

//go:generate oapi-codegen --config=cfg.yaml ../../../search/openapi.json
