apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "hev-shop.configName" . }}
  labels:
    {{- include "hev-shop.labels" . | nindent 4 }}
data:
  LAYER_GATEWAY_URL: {{ .Values.layer.gatewayUrl | quote }}
  TURBOPUFFER_NAMESPACE: {{ .Values.pipeline.product.namespace | quote }}
  EXTRACTION_PIPELINE_ID: {{ .Values.pipeline.extraction.id | quote }}
  PIPELINE_ID: {{ .Values.pipeline.product.id | quote }}
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
