{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hev-shop.secretName" . }}
  labels:
    {{- include "hev-shop.labels" . | nindent 4 }}
type: Opaque
stringData:
  HF_TOKEN: {{ .Values.secrets.hfToken | trim | quote }}
  LAYER_GATEWAY_API_KEY: {{ .Values.secrets.layerApiKey | trim | quote }}
{{- end }}
