apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: hev-shop
resources:
  - namespace.yaml
  - pvc.yaml
  - secret.yaml
  - configmap.yaml
  - api-deployment.yaml
  - api-service.yaml
  - cpu-worker-deployment.yaml
  - cpu-worker-scaledobject.yaml
  - gpu-worker-deployment.yaml
  - gpu-worker-scaledobject.yaml
  - review-embed-worker-deployment.yaml
  - review-embed-worker-scaledobject.yaml
  - review-classify-worker-deployment.yaml
  - review-classify-worker-scaledobject.yaml
  - review-aggregate-worker-deployment.yaml
  - review-aggregate-worker-scaledobject.yaml
  - web-deployment.yaml
  - web-service.yaml
images:
  - name: hev-shop-indexer
    newName: ghcr.io/hev/hev-shop-indexer
    newTag: latest
  - name: hev-shop-web
    newName: ghcr.io/hev/hev-shop-web
    newTag: latest
