apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hev-shop-data
  labels:
    app.kubernetes.io/name: hev-shop
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: hev-shop-efs
  resources:
    requests:
      storage: 100Gi
