// Package searchapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package searchapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// CategoryBucket defines model for CategoryBucket.
type CategoryBucket struct {
	DocCount int    `json:"doc_count"`
	Value    string `json:"value"`
}

// CountInfo Result of a /v2/namespaces/{ns}/result-count fan-out. `bounded=True` means
// one or more shards saturated their top_k cap on this round, so `count`
// is a lower bound — render it as "≥N" rather than "=N".
type CountInfo struct {
	Bounded bool `json:"bounded"`
	Count   int  `json:"count"`

	// LayerPerf One Layer gateway round-trip's timing + cache disposition,
	// surfaced to the UI so the showcase can render `42ms · cache hit`
	// inline. `cache_status` is the gateway's `x-layer-cache` header
	// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
	// didn't attach the header — the `query` endpoint doesn't go through
	// the document cache, so query perfs always have `cache_status=None`.
	LayerPerf       *LayerPerf `json:"layer_perf,omitempty"`
	MaxDistance     float32    `json:"max_distance"`
	ShardsSaturated *int       `json:"shards_saturated,omitempty"`
	ShardsTotal     *int       `json:"shards_total,omitempty"`
	TimedOut        *bool      `json:"timed_out,omitempty"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// LayerPerf One Layer gateway round-trip's timing + cache disposition,
// surfaced to the UI so the showcase can render `42ms · cache hit`
// inline. `cache_status` is the gateway's `x-layer-cache` header
// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
// didn't attach the header — the `query` endpoint doesn't go through
// the document cache, so query perfs always have `cache_status=None`.
type LayerPerf struct {
	CacheStatus *string `json:"cache_status,omitempty"`
	LatencyMs   int     `json:"latency_ms"`
}

// MetaResponse defines model for MetaResponse.
type MetaResponse struct {
	Categories []CategoryBucket `json:"categories"`
	IsStable   *bool            `json:"is_stable,omitempty"`

	// LayerPerf One Layer gateway round-trip's timing + cache disposition,
	// surfaced to the UI so the showcase can render `42ms · cache hit`
	// inline. `cache_status` is the gateway's `x-layer-cache` header
	// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
	// didn't attach the header — the `query` endpoint doesn't go through
	// the document cache, so query perfs always have `cache_status=None`.
	LayerPerf  *LayerPerf `json:"layer_perf,omitempty"`
	Namespace  string     `json:"namespace"`
	StableAsOf *int       `json:"stable_as_of,omitempty"`
	Vectors    int        `json:"vectors"`
}

// ProductResponse defines model for ProductResponse.
type ProductResponse struct {
	Asin       string                  `json:"asin"`
	Attributes *map[string]interface{} `json:"attributes,omitempty"`

	// LayerPerf One Layer gateway round-trip's timing + cache disposition,
	// surfaced to the UI so the showcase can render `42ms · cache hit`
	// inline. `cache_status` is the gateway's `x-layer-cache` header
	// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
	// didn't attach the header — the `query` endpoint doesn't go through
	// the document cache, so query perfs always have `cache_status=None`.
	LayerPerf *LayerPerf `json:"layer_perf,omitempty"`
	Namespace string     `json:"namespace"`
}

// RecommendRequest defines model for RecommendRequest.
type RecommendRequest struct {
	// Asin Seed product ASIN
	Asin              string    `json:"asin"`
	Category          *string   `json:"category,omitempty"`
	IncludeAttributes *[]string `json:"include_attributes,omitempty"`
	Namespace         *string   `json:"namespace,omitempty"`
	TopK              *int      `json:"top_k,omitempty"`
}

// RecommendResponse defines model for RecommendResponse.
type RecommendResponse struct {
	Asin string      `json:"asin"`
	Hits []SearchHit `json:"hits"`

	// LayerPerf One Layer gateway round-trip's timing + cache disposition,
	// surfaced to the UI so the showcase can render `42ms · cache hit`
	// inline. `cache_status` is the gateway's `x-layer-cache` header
	// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
	// didn't attach the header — the `query` endpoint doesn't go through
	// the document cache, so query perfs always have `cache_status=None`.
	LayerPerf  *LayerPerf `json:"layer_perf,omitempty"`
	Namespace  string     `json:"namespace"`
	NextCursor *string    `json:"next_cursor,omitempty"`
	StableAsOf *int       `json:"stable_as_of,omitempty"`
}

// SearchHit defines model for SearchHit.
type SearchHit struct {
	Attributes *map[string]interface{} `json:"attributes,omitempty"`
	Dist       *float32                `json:"dist,omitempty"`
	Id         string                  `json:"id"`
}

// SearchRequest defines model for SearchRequest.
type SearchRequest struct {
	Category *string `json:"category,omitempty"`

	// Cursor Opaque pagination cursor from a prior /search response's next_cursor. Re-send the same query/filters/top_k to keep paging consistent; the gateway re-applies the consistency watermark.
	Cursor            *string   `json:"cursor,omitempty"`
	IncludeAttributes *[]string `json:"include_attributes,omitempty"`

	// MaxDistance Cosine-distance ceiling for with_count. 0.4 is tight ("results worth showing"); raise toward 1.0 for looser totals.
	MaxDistance *float32 `json:"max_distance,omitempty"`
	Namespace   *string  `json:"namespace,omitempty"`

	// Query Free-text search query
	Query string `json:"query"`
	TopK  *int   `json:"top_k,omitempty"`

	// WithCount If true, fan out an extra /v2/namespaces/{ns}/result-count call against the same query vector + filters to estimate how many docs sit within max_distance. Costs one extra round-trip.
	WithCount *bool `json:"with_count,omitempty"`
}

// SearchResponse defines model for SearchResponse.
type SearchResponse struct {
	// Count Result of a /v2/namespaces/{ns}/result-count fan-out. `bounded=True` means
	// one or more shards saturated their top_k cap on this round, so `count`
	// is a lower bound — render it as "≥N" rather than "=N".
	Count *CountInfo  `json:"count,omitempty"`
	Hits  []SearchHit `json:"hits"`

	// LayerPerf One Layer gateway round-trip's timing + cache disposition,
	// surfaced to the UI so the showcase can render `42ms · cache hit`
	// inline. `cache_status` is the gateway's `x-layer-cache` header
	// (`"hit"`, `"miss"`, or `"miss-on-error"`); `None` when the gateway
	// didn't attach the header — the `query` endpoint doesn't go through
	// the document cache, so query perfs always have `cache_status=None`.
	LayerPerf *LayerPerf `json:"layer_perf,omitempty"`
	Namespace string     `json:"namespace"`

	// NextCursor Opaque cursor for the next page. Present iff the gateway returned a full top_k (i.e. there may be more results). Pass it back as `cursor` on the next /search call alongside the same filters.
	NextCursor *string `json:"next_cursor,omitempty"`
	Query      string  `json:"query"`

	// StableAsOf Epoch-ms watermark — results reflect everything indexed at or before this timestamp. None until the gateway's consistency watcher has observed a clean snapshot for the namespace.
	StableAsOf *int `json:"stable_as_of,omitempty"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// MetaMetaGetParams defines parameters for MetaMetaGet.
type MetaMetaGetParams struct {
	Namespace *string `form:"namespace,omitempty" json:"namespace,omitempty"`
}

// RecommendRecommendPostJSONRequestBody defines body for RecommendRecommendPost for application/json ContentType.
type RecommendRecommendPostJSONRequestBody = RecommendRequest

// SearchSearchPostJSONRequestBody defines body for SearchSearchPost for application/json ContentType.
type SearchSearchPostJSONRequestBody = SearchRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthzHealthzGet request
	HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// MetaMetaGet request
	MetaMetaGet(ctx context.Context, params *MetaMetaGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ProductProductAsinGet request
	ProductProductAsinGet(ctx context.Context, asin string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// RecommendRecommendPostWithBody request with any body
	RecommendRecommendPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	RecommendRecommendPost(ctx context.Context, body RecommendRecommendPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SearchSearchPostWithBody request with any body
	SearchSearchPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SearchSearchPost(ctx context.Context, body SearchSearchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzHealthzGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) MetaMetaGet(ctx context.Context, params *MetaMetaGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewMetaMetaGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ProductProductAsinGet(ctx context.Context, asin string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewProductProductAsinGetRequest(c.Server, asin)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecommendRecommendPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecommendRecommendPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) RecommendRecommendPost(ctx context.Context, body RecommendRecommendPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewRecommendRecommendPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchSearchPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchSearchPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SearchSearchPost(ctx context.Context, body SearchSearchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSearchSearchPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthzHealthzGetRequest generates requests for HealthzHealthzGet
func NewHealthzHealthzGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewMetaMetaGetRequest generates requests for MetaMetaGet
func NewMetaMetaGetRequest(server string, params *MetaMetaGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/meta")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Namespace != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "namespace", *params.Namespace, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewProductProductAsinGetRequest generates requests for ProductProductAsinGet
func NewProductProductAsinGetRequest(server string, asin string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "asin", asin, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/product/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewRecommendRecommendPostRequest calls the generic RecommendRecommendPost builder with application/json body
func NewRecommendRecommendPostRequest(server string, body RecommendRecommendPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewRecommendRecommendPostRequestWithBody(server, "application/json", bodyReader)
}

// NewRecommendRecommendPostRequestWithBody generates requests for RecommendRecommendPost with any type of body
func NewRecommendRecommendPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/recommend")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewSearchSearchPostRequest calls the generic SearchSearchPost builder with application/json body
func NewSearchSearchPostRequest(server string, body SearchSearchPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSearchSearchPostRequestWithBody(server, "application/json", bodyReader)
}

// NewSearchSearchPostRequestWithBody generates requests for SearchSearchPost with any type of body
func NewSearchSearchPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthzHealthzGetWithResponse request
	HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error)

	// MetaMetaGetWithResponse request
	MetaMetaGetWithResponse(ctx context.Context, params *MetaMetaGetParams, reqEditors ...RequestEditorFn) (*MetaMetaGetResponse, error)

	// ProductProductAsinGetWithResponse request
	ProductProductAsinGetWithResponse(ctx context.Context, asin string, reqEditors ...RequestEditorFn) (*ProductProductAsinGetResponse, error)

	// RecommendRecommendPostWithBodyWithResponse request with any body
	RecommendRecommendPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecommendRecommendPostResponse, error)

	RecommendRecommendPostWithResponse(ctx context.Context, body RecommendRecommendPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RecommendRecommendPostResponse, error)

	// SearchSearchPostWithBodyWithResponse request with any body
	SearchSearchPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchSearchPostResponse, error)

	SearchSearchPostWithResponse(ctx context.Context, body SearchSearchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchSearchPostResponse, error)
}

type HealthzHealthzGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]string
}

// Status returns HTTPResponse.Status
func (r HealthzHealthzGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzHealthzGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzHealthzGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type MetaMetaGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MetaResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r MetaMetaGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r MetaMetaGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r MetaMetaGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ProductProductAsinGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ProductResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ProductProductAsinGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ProductProductAsinGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ProductProductAsinGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type RecommendRecommendPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RecommendResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r RecommendRecommendPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r RecommendRecommendPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r RecommendRecommendPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type SearchSearchPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *SearchResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r SearchSearchPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SearchSearchPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r SearchSearchPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthzHealthzGetWithResponse request returning *HealthzHealthzGetResponse
func (c *ClientWithResponses) HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error) {
	rsp, err := c.HealthzHealthzGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzHealthzGetResponse(rsp)
}

// MetaMetaGetWithResponse request returning *MetaMetaGetResponse
func (c *ClientWithResponses) MetaMetaGetWithResponse(ctx context.Context, params *MetaMetaGetParams, reqEditors ...RequestEditorFn) (*MetaMetaGetResponse, error) {
	rsp, err := c.MetaMetaGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseMetaMetaGetResponse(rsp)
}

// ProductProductAsinGetWithResponse request returning *ProductProductAsinGetResponse
func (c *ClientWithResponses) ProductProductAsinGetWithResponse(ctx context.Context, asin string, reqEditors ...RequestEditorFn) (*ProductProductAsinGetResponse, error) {
	rsp, err := c.ProductProductAsinGet(ctx, asin, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseProductProductAsinGetResponse(rsp)
}

// RecommendRecommendPostWithBodyWithResponse request with arbitrary body returning *RecommendRecommendPostResponse
func (c *ClientWithResponses) RecommendRecommendPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*RecommendRecommendPostResponse, error) {
	rsp, err := c.RecommendRecommendPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecommendRecommendPostResponse(rsp)
}

func (c *ClientWithResponses) RecommendRecommendPostWithResponse(ctx context.Context, body RecommendRecommendPostJSONRequestBody, reqEditors ...RequestEditorFn) (*RecommendRecommendPostResponse, error) {
	rsp, err := c.RecommendRecommendPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseRecommendRecommendPostResponse(rsp)
}

// SearchSearchPostWithBodyWithResponse request with arbitrary body returning *SearchSearchPostResponse
func (c *ClientWithResponses) SearchSearchPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SearchSearchPostResponse, error) {
	rsp, err := c.SearchSearchPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchSearchPostResponse(rsp)
}

func (c *ClientWithResponses) SearchSearchPostWithResponse(ctx context.Context, body SearchSearchPostJSONRequestBody, reqEditors ...RequestEditorFn) (*SearchSearchPostResponse, error) {
	rsp, err := c.SearchSearchPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSearchSearchPostResponse(rsp)
}

// ParseHealthzHealthzGetResponse parses an HTTP response from a HealthzHealthzGetWithResponse call
func ParseHealthzHealthzGetResponse(rsp *http.Response) (*HealthzHealthzGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzHealthzGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseMetaMetaGetResponse parses an HTTP response from a MetaMetaGetWithResponse call
func ParseMetaMetaGetResponse(rsp *http.Response) (*MetaMetaGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &MetaMetaGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MetaResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseProductProductAsinGetResponse parses an HTTP response from a ProductProductAsinGetWithResponse call
func ParseProductProductAsinGetResponse(rsp *http.Response) (*ProductProductAsinGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ProductProductAsinGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ProductResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseRecommendRecommendPostResponse parses an HTTP response from a RecommendRecommendPostWithResponse call
func ParseRecommendRecommendPostResponse(rsp *http.Response) (*RecommendRecommendPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &RecommendRecommendPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RecommendResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseSearchSearchPostResponse parses an HTTP response from a SearchSearchPostWithResponse call
func ParseSearchSearchPostResponse(rsp *http.Response) (*SearchSearchPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SearchSearchPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest SearchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
