// Package indexerapi is a typed HTTP client for the hev-shop indexer
// control plane.
//
// The body of this package is generated by oapi-codegen v2 from the
// committed OpenAPI spec at ../../../indexer/openapi.json. Regenerate with:
//
//	make codegen   # or: go generate ./...
package indexerapi

//go:generate oapi-codegen --config=cfg.yaml ../../../indexer/openapi.json
