// Package indexerapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package indexerapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

// CheckpointActivationRequest defines model for CheckpointActivationRequest.
type CheckpointActivationRequest struct {
	// AllowFailed If false, any failed documents block checkpoint activation.
	AllowFailed *bool `json:"allow_failed,omitempty"`

	// CatalogRunId Catalog checkpoint label. Defaults to catalog-YYYY-MM-DD in UTC.
	CatalogRunId *string `json:"catalog_run_id,omitempty"`
}

// CheckpointActivationResponse defines model for CheckpointActivationResponse.
type CheckpointActivationResponse struct {
	CatalogRunId string                       `json:"catalog_run_id"`
	Checkpoint   map[string]interface{}       `json:"checkpoint"`
	Namespace    string                       `json:"namespace"`
	Pipelines    map[string]PipelineStability `json:"pipelines"`
}

// HTTPValidationError defines model for HTTPValidationError.
type HTTPValidationError struct {
	Detail *[]ValidationError `json:"detail,omitempty"`
}

// IndexCategoryResponse defines model for IndexCategoryResponse.
type IndexCategoryResponse struct {
	Category    string `json:"category"`
	Count       int    `json:"count"`
	JobsCreated int    `json:"jobs_created"`
}

// IndexRequest defines model for IndexRequest.
type IndexRequest struct {
	// CatalogRunId Catalog checkpoint label. Defaults to catalog-YYYY-MM-DD in UTC; activate it with POST /index/checkpoint after ingest stabilizes.
	CatalogRunId *string `json:"catalog_run_id,omitempty"`

	// Categories Optional multi-category fan-out. Overrides category unless category is explicitly merged by the caller.
	Categories *[]string `json:"categories,omitempty"`
	Category   *string   `json:"category,omitempty"`

	// Count -1 indexes all rows in one job
	Count   *int `json:"count,omitempty"`
	JobSize *int `json:"job_size,omitempty"`
}

// IndexResponse defines model for IndexResponse.
type IndexResponse struct {
	CatalogRunId string                   `json:"catalog_run_id"`
	Categories   *[]IndexCategoryResponse `json:"categories,omitempty"`
	Category     string                   `json:"category"`
	Count        int                      `json:"count"`
	JobsCreated  int                      `json:"jobs_created"`
	Namespace    string                   `json:"namespace"`
	PipelineId   string                   `json:"pipeline_id"`
}

// PipelineStability defines model for PipelineStability.
type PipelineStability struct {
	FailedCount     *int  `json:"failed_count,omitempty"`
	PendingCount    *int  `json:"pending_count,omitempty"`
	ProcessingCount *int  `json:"processing_count,omitempty"`
	Stable          *bool `json:"stable,omitempty"`
}

// StatusResponse defines model for StatusResponse.
type StatusResponse struct {
	Extraction *map[string]interface{} `json:"extraction,omitempty"`
	Jobs       map[string]int          `json:"jobs"`
	Layer      map[string]interface{}  `json:"layer"`
	PipelineId string                  `json:"pipeline_id"`
}

// ValidationError defines model for ValidationError.
type ValidationError struct {
	Ctx   *map[string]interface{}    `json:"ctx,omitempty"`
	Input interface{}                `json:"input,omitempty"`
	Loc   []ValidationError_Loc_Item `json:"loc"`
	Msg   string                     `json:"msg"`
	Type  string                     `json:"type"`
}

// ValidationErrorLoc0 defines model for .
type ValidationErrorLoc0 = string

// ValidationErrorLoc1 defines model for .
type ValidationErrorLoc1 = int

// ValidationError_Loc_Item defines model for ValidationError.loc.Item.
type ValidationError_Loc_Item struct {
	union json.RawMessage
}

// StatusStatusGetParams defines parameters for StatusStatusGet.
type StatusStatusGetParams struct {
	PipelineId *string `form:"pipeline_id,omitempty" json:"pipeline_id,omitempty"`
}

// IndexProductsIndexPostJSONRequestBody defines body for IndexProductsIndexPost for application/json ContentType.
type IndexProductsIndexPostJSONRequestBody = IndexRequest

// ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody defines body for ActivateCatalogCheckpointIndexCheckpointPost for application/json ContentType.
type ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody = CheckpointActivationRequest

// AsValidationErrorLoc0 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc0
func (t ValidationError_Loc_Item) AsValidationErrorLoc0() (ValidationErrorLoc0, error) {
	var body ValidationErrorLoc0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc0 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) FromValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc0 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc0
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc0(v ValidationErrorLoc0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsValidationErrorLoc1 returns the union data inside the ValidationError_Loc_Item as a ValidationErrorLoc1
func (t ValidationError_Loc_Item) AsValidationErrorLoc1() (ValidationErrorLoc1, error) {
	var body ValidationErrorLoc1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromValidationErrorLoc1 overwrites any union data inside the ValidationError_Loc_Item as the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) FromValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeValidationErrorLoc1 performs a merge with any union data inside the ValidationError_Loc_Item, using the provided ValidationErrorLoc1
func (t *ValidationError_Loc_Item) MergeValidationErrorLoc1(v ValidationErrorLoc1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t ValidationError_Loc_Item) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *ValidationError_Loc_Item) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// HealthzHealthzGet request
	HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IndexProductsIndexPostWithBody request with any body
	IndexProductsIndexPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	IndexProductsIndexPost(ctx context.Context, body IndexProductsIndexPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ActivateCatalogCheckpointIndexCheckpointPostWithBody request with any body
	ActivateCatalogCheckpointIndexCheckpointPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	ActivateCatalogCheckpointIndexCheckpointPost(ctx context.Context, body ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// StatusStatusGet request
	StatusStatusGet(ctx context.Context, params *StatusStatusGetParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) HealthzHealthzGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthzHealthzGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IndexProductsIndexPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIndexProductsIndexPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) IndexProductsIndexPost(ctx context.Context, body IndexProductsIndexPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIndexProductsIndexPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ActivateCatalogCheckpointIndexCheckpointPostWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateCatalogCheckpointIndexCheckpointPostRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) ActivateCatalogCheckpointIndexCheckpointPost(ctx context.Context, body ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewActivateCatalogCheckpointIndexCheckpointPostRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) StatusStatusGet(ctx context.Context, params *StatusStatusGetParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewStatusStatusGetRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewHealthzHealthzGetRequest generates requests for HealthzHealthzGet
func NewHealthzHealthzGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/healthz")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewIndexProductsIndexPostRequest calls the generic IndexProductsIndexPost builder with application/json body
func NewIndexProductsIndexPostRequest(server string, body IndexProductsIndexPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewIndexProductsIndexPostRequestWithBody(server, "application/json", bodyReader)
}

// NewIndexProductsIndexPostRequestWithBody generates requests for IndexProductsIndexPost with any type of body
func NewIndexProductsIndexPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewActivateCatalogCheckpointIndexCheckpointPostRequest calls the generic ActivateCatalogCheckpointIndexCheckpointPost builder with application/json body
func NewActivateCatalogCheckpointIndexCheckpointPostRequest(server string, body ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewActivateCatalogCheckpointIndexCheckpointPostRequestWithBody(server, "application/json", bodyReader)
}

// NewActivateCatalogCheckpointIndexCheckpointPostRequestWithBody generates requests for ActivateCatalogCheckpointIndexCheckpointPost with any type of body
func NewActivateCatalogCheckpointIndexCheckpointPostRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/index/checkpoint")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewStatusStatusGetRequest generates requests for StatusStatusGet
func NewStatusStatusGetRequest(server string, params *StatusStatusGetParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/status")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.PipelineId != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "pipeline_id", *params.PipelineId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// HealthzHealthzGetWithResponse request
	HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error)

	// IndexProductsIndexPostWithBodyWithResponse request with any body
	IndexProductsIndexPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IndexProductsIndexPostResponse, error)

	IndexProductsIndexPostWithResponse(ctx context.Context, body IndexProductsIndexPostJSONRequestBody, reqEditors ...RequestEditorFn) (*IndexProductsIndexPostResponse, error)

	// ActivateCatalogCheckpointIndexCheckpointPostWithBodyWithResponse request with any body
	ActivateCatalogCheckpointIndexCheckpointPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ActivateCatalogCheckpointIndexCheckpointPostResponse, error)

	ActivateCatalogCheckpointIndexCheckpointPostWithResponse(ctx context.Context, body ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody, reqEditors ...RequestEditorFn) (*ActivateCatalogCheckpointIndexCheckpointPostResponse, error)

	// StatusStatusGetWithResponse request
	StatusStatusGetWithResponse(ctx context.Context, params *StatusStatusGetParams, reqEditors ...RequestEditorFn) (*StatusStatusGetResponse, error)
}

type HealthzHealthzGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *map[string]string
}

// Status returns HTTPResponse.Status
func (r HealthzHealthzGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthzHealthzGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r HealthzHealthzGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type IndexProductsIndexPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *IndexResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r IndexProductsIndexPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IndexProductsIndexPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r IndexProductsIndexPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ActivateCatalogCheckpointIndexCheckpointPostResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *CheckpointActivationResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r ActivateCatalogCheckpointIndexCheckpointPostResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ActivateCatalogCheckpointIndexCheckpointPostResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ActivateCatalogCheckpointIndexCheckpointPostResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type StatusStatusGetResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *StatusResponse
	JSON422      *HTTPValidationError
}

// Status returns HTTPResponse.Status
func (r StatusStatusGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r StatusStatusGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r StatusStatusGetResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// HealthzHealthzGetWithResponse request returning *HealthzHealthzGetResponse
func (c *ClientWithResponses) HealthzHealthzGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthzHealthzGetResponse, error) {
	rsp, err := c.HealthzHealthzGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthzHealthzGetResponse(rsp)
}

// IndexProductsIndexPostWithBodyWithResponse request with arbitrary body returning *IndexProductsIndexPostResponse
func (c *ClientWithResponses) IndexProductsIndexPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IndexProductsIndexPostResponse, error) {
	rsp, err := c.IndexProductsIndexPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIndexProductsIndexPostResponse(rsp)
}

func (c *ClientWithResponses) IndexProductsIndexPostWithResponse(ctx context.Context, body IndexProductsIndexPostJSONRequestBody, reqEditors ...RequestEditorFn) (*IndexProductsIndexPostResponse, error) {
	rsp, err := c.IndexProductsIndexPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIndexProductsIndexPostResponse(rsp)
}

// ActivateCatalogCheckpointIndexCheckpointPostWithBodyWithResponse request with arbitrary body returning *ActivateCatalogCheckpointIndexCheckpointPostResponse
func (c *ClientWithResponses) ActivateCatalogCheckpointIndexCheckpointPostWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*ActivateCatalogCheckpointIndexCheckpointPostResponse, error) {
	rsp, err := c.ActivateCatalogCheckpointIndexCheckpointPostWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateCatalogCheckpointIndexCheckpointPostResponse(rsp)
}

func (c *ClientWithResponses) ActivateCatalogCheckpointIndexCheckpointPostWithResponse(ctx context.Context, body ActivateCatalogCheckpointIndexCheckpointPostJSONRequestBody, reqEditors ...RequestEditorFn) (*ActivateCatalogCheckpointIndexCheckpointPostResponse, error) {
	rsp, err := c.ActivateCatalogCheckpointIndexCheckpointPost(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseActivateCatalogCheckpointIndexCheckpointPostResponse(rsp)
}

// StatusStatusGetWithResponse request returning *StatusStatusGetResponse
func (c *ClientWithResponses) StatusStatusGetWithResponse(ctx context.Context, params *StatusStatusGetParams, reqEditors ...RequestEditorFn) (*StatusStatusGetResponse, error) {
	rsp, err := c.StatusStatusGet(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseStatusStatusGetResponse(rsp)
}

// ParseHealthzHealthzGetResponse parses an HTTP response from a HealthzHealthzGetWithResponse call
func ParseHealthzHealthzGetResponse(rsp *http.Response) (*HealthzHealthzGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthzHealthzGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest map[string]string
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseIndexProductsIndexPostResponse parses an HTTP response from a IndexProductsIndexPostWithResponse call
func ParseIndexProductsIndexPostResponse(rsp *http.Response) (*IndexProductsIndexPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IndexProductsIndexPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IndexResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseActivateCatalogCheckpointIndexCheckpointPostResponse parses an HTTP response from a ActivateCatalogCheckpointIndexCheckpointPostWithResponse call
func ParseActivateCatalogCheckpointIndexCheckpointPostResponse(rsp *http.Response) (*ActivateCatalogCheckpointIndexCheckpointPostResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ActivateCatalogCheckpointIndexCheckpointPostResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CheckpointActivationResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}

// ParseStatusStatusGetResponse parses an HTTP response from a StatusStatusGetWithResponse call
func ParseStatusStatusGetResponse(rsp *http.Response) (*StatusStatusGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &StatusStatusGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest StatusResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 422:
		var dest HTTPValidationError
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON422 = &dest

	}

	return response, nil
}
